name: screen_navigate
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.5.4
  google_fonts: ^6.2.1
  get: ^4.6.6
  image_picker: ^1.1.2

  cupertino_icons: ^1.0.8
  http: ^1.2.2
  url_launcher: ^6.3.1
  intl: ^0.19.0




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
